url: https://bigodatamining.github.io/
#baseurl:

# Site settings
title: BigODM Lab
email: hjdai@nttu.edu.tw
description: "Big biOmedical (BigO) Data Mining Lab"

# Team names, titles and social links
people:
- name: Hong-Jie Dai
  pic: 1
  position: Lab Director, Assistant Professor of Department of Computer Science and Information Engineering and Chief of Systems Development Section of Library and Information Center of National Taitung University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/hong-jie-dai-990a9625
    - title: facebook
      url: https://www.facebook.com/hongjie.dai
    #- title: stack-overflow
    #  url: #

- name: Chen-Kai Wang
  pic: 2
  position: Intern at Intelligent Agents Systems Lab of Institute of Information Science of Academia Sinica, Master Student of Graduate Institute of Biomedical Informatics of Taipei Medical University
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/chen-kai-wang-022077132
    - title: facebook
      url: https://www.facebook.com/chenkai.wang.12
    #- title: twitter
    #  url: #
- name: Onkar Singh
  pic: 3
  position: PhD Student of Bioinformatics of Institute of Information Science of Taiwan International Graduate Program of Academia Sinica
  social:
     - title: facebook
       url: https://www.facebook.com/onkar.singh.735
#    - title: twitter
#      url: #
#    - title: google-plus
#      url: #
- name: Nai-Wen Chang
  pic: 4
  position: Research assistant of Intelligent Agent Systems Lab of Institute of Information Science of Academia Sinica, PhD Student of Bioinformatics of Graduate Institute of Biomedical Electronics and Bioinformatics of National Taiwan University
  social:
     -title: facebook
      url: https://www.facebook.com/naiwun
#     -title: twitter
#      url: #
#     -title: google-plus
#      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/BigODataMining/
  - title: facebook
    url: https://www.facebook.com/groups/404559626383286/

# Postal address (add as many lines as necessary)
address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
